### ISSUE TITLE
Backend: product content description - store view specific - not stored: Type Error

### ISSUE THREAD

**Issue by ricoliv** [magento/magento2#35361]
### Preconditions (*)

1. Magento Version 2.2.9
2. Multiple Store views are enanbled (same product catalog, store views = different languages in this case)
3. Products from Magento 1.x have been ported some time ago, works fine in Version 2.2.9 with different languages

### Steps to reproduce (*)

1. Utilize Magento 2.2.9 with multiple store views.
2. Go to Backend Admin
3. Generate and save new product in Magento 2.2.9 default store view - product is availabe in all views then
4. switch to other, non-default store view and click "Use Default Value" Checkbox on Fields Content-Description or Content-Short Description
5. Text Field of Description does NOT turn from gray to black, but it can be edited
6. Note: For other "Use Default Value" Checkboxes, e.g. like the one on Enable Product on the top, the field turns from gray to black
7. After text field Description is edited and saved, after refresh, the product details show previous default storeview text again
8. Store view specific text Description and Short Description can not be saved.

### Expected result (*)

1. I expect store view specific Descriptions and Short Descriptions can be saved, just like before in Magento 1.x
2.

### Actual result (*)

1. Store view specific text Description and Short Description can not be saved.
2. When debugging in Browser console, we noted an error message when clicking the Checkbox "Use Default value"
3. Error Message is: Uncaught TypeError: this.$wysiwygEditorButton.attr is not a function
4. Please see screenshot attached 
5. I'm not a Magento expert, I don't know, if this is in relation to the problem
6. Workaround I would go, if issue not solved: I would try to copy the Description text directly into SQL

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
![Store View](https://user-images.githubusercontent.com/30410373/164981187-fcbfbcb4-bdcb-49e1-913d-b254268adc1a.jpg)

**Comment by ricoliv** [comment]
I have gone the workaround path now: when INSERTING a new line into SQL for Shop ID together with Description and Short Description  (75, 76), the text can be edited and stored via the admin backend again. 

So to me it looks like the Uncought Type Error described above is in relation to the problem.

**Comment by ricoliv** [comment]
I am not sure, but there might be another prerequisite setting for this error to occur:
Stores-Configuration-General-Content Management-Enable WYSIWYG Editor is "DISABLED COMPLETELY"

**Comment by engcom-November** [comment]
Hi @ricoliv ,
We are closing this issue as there has been no latest update on the same. Kindly reopen / create new issue if you are still facing any issues.
Thank you.
