### ISSUE TITLE
Product grid has quantity in decimals

### ISSUE THREAD

**Issue by Zyles** [magento/magento2#26302]
### Preconditions (*)

1. Magento 2.3.3, 2.4-develop

### Steps to reproduce (*)

1. Install
2. Add product
3. Go to products grid

### Expected result (*)

Don't know about you, but we don't sell goods in fractions.

Show product quantity without decimals.

### Actual result (*)

Product quantity with decimals.

![image](https://user-images.githubusercontent.com/1741593/71955802-9a0e7080-31e9-11ea-8362-2f70c7b0789f.png)

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @ajijshekh123 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-30271` were created

**Issue Available**: @ajijshekh123, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by ajijshekh123** [comment]
@Zyles - This issue related to the below one:
https://github.com/magento/magento2/issues/6713
Please review this issue and Let me know Should I close this issue or not?

Thanks.

**Comment by sunilit42** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @sunilit42. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sunilit42, here is your [Magento instance](https://i-26302-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26302-2-4-develop.instances.magento-community.engineering/admin](https://i-26302-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Zyles** [comment]
> @Zyles - This issue related to the below one:
> #6713
> Please review this issue and Let me know Should I close this issue or not?
> 
> Thanks.

Yes looks like same problem again.

**Comment by ajijshekh123** [comment]
Okay @Zyles

**Comment by mrtuvn** [comment]
Fount qty column is inconsistent in current code base. Some place define this value in decimal and some place use int

**Comment by gaurav-473** [comment]
@magento give me 2.4-develop instance - upcoming 2.4.x release

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @gauravagarwal1001, here is your [Magento instance](https://i-26302-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26302-2-4-develop.instances.magento-community.engineering/admin](https://i-26302-2-4-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by madhu-ranosys** [comment]
I am getting error to submit pull request. Please suggest how to submit pull request.
Pull request creation failed. The fix-issue-26302 branch doesn’t exist.  
![image](https://user-images.githubusercontent.com/59955325/75323485-ff521a00-589a-11ea-8b0a-80bdd9196ae4.png)

**Comment by gwharton** [comment]
Some people do sell products in decimals. There is a setting for it in advanced inventory.

**Comment by Zyles** [comment]
> Some people do sell products in decimals. There is a setting for it in advanced inventory.

There is no such thing in Magento 2. Maybe you mean MSI. And we do not use it and still have decimals.

**Comment by gwharton** [comment]
Stock Magento 2

![image](https://user-images.githubusercontent.com/30697781/78126834-0d9bd480-740b-11ea-8f0b-4cd1aad56c2f.png)

![image](https://user-images.githubusercontent.com/30697781/78126897-24422b80-740b-11ea-9d23-2d7f65034d67.png)

**Comment by gwharton** [comment]
People may sell products by other attributes such as volume, or length, where decimals in quantity is important. The PR raised against this issue needs to be updated so it checks the value of that setting for each product before determining whether it should be displayed as an integer or decimal.

**Comment by Zyles** [comment]
Let me repeat myself.

There is no "Advanced Inventory"

Why you are mixing MSI into this issue is unclear.

**Comment by Zyles** [comment]
Now I see where you get "Advanced Inventory" from. On the product. But it still is not right;

![image](https://user-images.githubusercontent.com/1741593/78128945-0d093b00-7417-11ea-946b-2ef6c680602d.png)

![image](https://user-images.githubusercontent.com/1741593/78128964-15617600-7417-11ea-9dc0-e1fa5e914a4f.png)

![image](https://user-images.githubusercontent.com/1741593/78128996-24482880-7417-11ea-83ee-114663b970fa.png)


The bug is still present.

**Comment by gwharton** [comment]
Yes, We are arguing for the same thing i think.

"Qty Use Decimals" = "No" THEN quantity input validation="int" ✅ AND Grid should display "3" ❌
"Qty Use Decimals" = "Yes" THEN quantity input validation="float" ✅ AND Grid should display "3.0000" ✅

The referenced PR does not implement the above.

**Comment by madhu-ranosys** [comment]
> Yes, We are arguing for the same thing i think.
> 
> "Qty Use Decimals" = "No" THEN quantity input validation="int" white_check_mark AND Grid should display "3" x
> "Qty Use Decimals" = "Yes" THEN quantity input validation="float" white_check_mark AND Grid should display "3.0000" white_check_mark
> 
> The referenced PR does not implement the above.

I have integrated it with the integer. I will check it with all product int and float and integrate for the same as above cases. Once updated will submit pull request.

**Comment by lenaorobei** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, here is your [Magento instance](https://i-26302-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26302-2-4-develop.instances.magento-community.engineering/admin_29b0](https://i-26302-2-4-develop.instances.magento-community.engineering/admin_29b0)
Login: `71e33dfd` Password: `2f44afd504d6`
Instance will be terminated in up to 3 hours.

**Comment by lenaorobei** [comment]
Hello @Zyles. This is not a bug, but expected behaviour. Please refer to the [Magento User Guide](https://docs.magento.com/m2/ce/user_guide/catalog/inventory-product-stock-options.html?itm_source=merchdocs_ce&itm_medium=quick_search&itm_campaign=federated_search&itm_term=). 
The `Quantity uses Decimals` serves for input validation and determines if customers can use a decimal value rather than a whole number when entering the quantity ordered. 

If you need to change the grid display you can create custom column rendered for that.

Thanks.

**Comment by Zyles** [comment]
WTF?

How is not a bug?

Did you even read the issue?

**Comment by cptX** [comment]
I absolutely agree with @Zyles! This is a bug and it makes zero sense to show decimals in the grid when the product quantity should have the setting to not use decimals. It makes reading the grid much more difficult!
Magento developers team continues to surprise me with their distorted perception of usability...
