### ISSUE TITLE
Magento 2.1.6 to 2.3.0 upgrade error - Cannot process definition to array for type enum

### ISSUE THREAD

**Issue by thakurakhilesh** [magento/magento2#19540]
Preconditions (*)

    Magento 2.1.6 community to  Magento 2.3.0 community
PHP  7.2.12
Steps to reproduce (*)
I disabled all extensions that I installled:Please find below list of enable and disable list of modules:
List of enabled modules:
Magento_Store
Magento_AdminNotification
Magento_Directory
Magento_Theme
Magento_Backend
Magento_Eav
Magento_Indexer
Magento_Variable
Magento_Customer
Magento_Config
Magento_Cms
Magento_Catalog
Magento_AdvancedPricingImportExport
Magento_Search
Magento_Amqp
Magento_Security
Magento_User
Magento_Authorization
Magento_Quote
Magento_Rule
Magento_Backup
Magento_SalesSequence
Magento_Bundle
Magento_GraphQl
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_Payment
Magento_CatalogInventory
Magento_Integration
Magento_EavGraphQl
Magento_CatalogImportExport
Magento_Sales
Magento_CatalogInventoryGraphQl
Magento_Cron
Magento_Msrp
Magento_CatalogRule
Magento_CatalogUrlRewrite
Magento_CatalogUrlRewriteGraphQl
Magento_Widget
Magento_Checkout
Magento_CheckoutAgreements
Magento_Vault
Magento_CmsGraphQl
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_ConfigurableImportExport
Magento_ConfigurableProduct
Magento_StoreGraphQl
Magento_ConfigurableProductSales
Magento_Contact
Magento_Cookie
Magento_Email
Magento_CurrencySymbol
Magento_CatalogSearch
Magento_Analytics
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_Downloadable
Magento_CatalogGraphQl
Magento_ImportExport
Magento_Paypal
Magento_BundleGraphQl
Magento_AdvancedSearch
Magento_Newsletter
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_ConfigurableProductGraphQl
Magento_GroupedImportExport
Magento_GroupedProduct
Magento_GroupedProductGraphQl
Magento_DownloadableImportExport
Amazon_Core
Magento_InstantPurchase
Magento_CatalogAnalytics
Magento_Shipping
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_MessageQueue
Magento_CatalogRuleConfigurable
Magento_Multishipping
Magento_MysqlMq
Magento_NewRelicReporting
Magento_ProductAlert
Magento_OfflinePayments
Magento_SalesRule
Magento_PageCache
Magento_Authorizenet
Magento_Braintree
Magento_Persistent
Magento_Reports
Magento_ProductVideo
Klarna_Core
Magento_QuoteAnalytics
Magento_QuoteGraphQl
Magento_ReleaseNotification
Magento_Review
Magento_RequireJs
Magento_SendFriend
Magento_ReviewAnalytics
Magento_Robots
Magento_Rss
Magento_Captcha
Magento_SalesAnalytics
Magento_SalesInventory
Magento_OfflineShipping
Amazon_Login
Magento_UrlRewrite
Magento_Elasticsearch
Magento_CustomerAnalytics
Magento_Wishlist
Magento_Signifyd
Magento_Sitemap
Amazon_Payment
Magento_DownloadableGraphQl
Magento_Webapi
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_Tinymce3
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_UrlRewriteGraphQl
Magento_AsynchronousOperations
Magento_Usps
Klarna_Ordermanagement
Klarna_Kp
Magento_Version
Magento_Swagger
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_Weee
Magento_WeeeGraphQl
Magento_CatalogWidget
Dotdigitalgroup_Email
Magento_WishlistAnalytics
Temando_Shipping
Vertex_Tax

List of disabled modules:
Aitoc_ReviewBooster
Amasty_Base
Amasty_Rolepermissions
IWD_All
IWD_StoreLocator
MSP_ReCaptcha
MageArray_Eventcalendar
Magebuzz_Socialshare
Magenest_Booking
MSP_TwoFactorAuth
Algolia_AlgoliaSearch
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryIndexer
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryReservations
Magento_InventoryReservationsApi
Magento_InventoryCache
Magento_InventorySalesAdminUi
Magento_InventorySalesApi
Magento_InventorySalesFrontendUi
Magento_InventoryShipping
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySourceSelectionApi
CzoneTech_AjaxifiedCatalog
Magento_InventoryShippingAdminUi
Magefan_Blog
Ortho_Theme
Ortho_Featuredproduct
Ortho_Newproduct
Ortho_Specialproduct
Ortho_Bestsellerproduct
Sourcefuse_Dealer
Sourcefuse_DealerProducts
Sourcefuse_Newsletter
Sourcefuse_Reserve
Sourcefuse_Sharpspring
Thai_S3
Ves_All
Ves_BaseWidget
Ves_Megamenu
Ves_PageBuilder
Ves_Setup
Yosto_RotateProduct

    bin/magento setup:upgrade

Expected result (*)

    Upgrade to complete

Actual result (*)
1. Error generated:

Cache cleared successfully
File system cleanup:
/var/www/html/kubota/generated/code/Composer
/var/www/html/kubota/generated/code/Magento
/var/www/html/kubota/generated/code/Symfony
Updating modules:
Schema creation/updates:
Cannot process definition to array for type enum
2. Nothing in log file related to issue. Only debug.log files generated.

**Comment by magento-engcom-team** [comment]
Hi @thakurakhilesh. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me $VERSION instance` 

where `$VERSION` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (for example: 2.3-develop). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@thakurakhilesh do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by magento-engcom-team** [comment]
Hi @engcom-backlog-nazar. Thank you for working on this issue. 
In order to make sure that issue has enough information and ready for development, please read and check the following instruction: :point_down:
- [ ] 1. Verify that issue has all the required information. (**Preconditions**, **Steps to reproduce**, **Expected result**, **Actual result**).<details><summary>Details</summary>If the issue has a valid description, the label `Issue: Format is valid` will be added to the issue automatically. Please, edit issue description if needed, until label `Issue: Format is valid` appears.</details>

- [ ] 2. Verify that issue has a meaningful description and provides enough information to reproduce the issue. If the report is valid, add `Issue: Clear Description` label to the issue by yourself.

- [ ] 3. Add `Component: XXXXX` label(s) to the ticket, indicating the components it may be related to.
- [ ] 4. Verify that the issue is reproducible on `2.3-develop` branch<details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.3-develop instance` to deploy test instance on Magento infrastructure. <br/> - If the issue is reproducible on `2.3-develop` branch, please, add the label `Reproduced on 2.3.x`.<br/>- If the issue is not reproducible, add your comment that issue is not reproducible and close the issue and **_stop verification process here_**!
</details>

- [ ] 5. Verify that the issue is reproducible on `2.2-develop` branch. <details><summary>Details</summary>- Add the comment `@magento-engcom-team give me 2.2-develop instance` to deploy test instance on Magento infrastructure. <br/>- If the issue is reproducible on `2.2-develop` branch, please add the label `Reproduced on 2.2.x`</details>

- [ ] 6. Add label `Issue: Confirmed` once verification is complete. 

- [ ] 7. Make sure that automatic system confirms that report has been added to the backlog.

**Comment by cscd98** [comment]
https://github.com/magento/magento2/issues/19479

**Comment by ghost** [comment]
Hi @thakurakhilesh i'm closing this ticket as this not related to core magento modules. Also please look one comment higher

**Comment by seyuf** [comment]
Similar error encountered on aurora dump to mysql rds aws.
After upgrade to 2.3 error at setup upgrade:
```
Array
(
    [name] => Column_priv
    [default] => 
    [type] => set
    [nullable] => 0
    [definition] => set('Select','Insert','Update','References')
    [extra] => 
    [comment] => 
)
Cannot process definition to array for type set
```
Column_priv is an aws generate table /column.

@engcom-backlog-nazar can this be reopened please?
Granted it is not related to core magento modules it is still an magento2 issue.
It would be nice if an solution could be found so that the setup upgrade does not fail when encountering incompatible types. Thanks

**Comment by thakurakhilesh** [comment]
Change customer module table column definition type

**Comment by thakurakhilesh** [comment]
Sorry custom not customer.
