### PR TITLE
Fix mage/translate resolving inherited prototype members as translations (#38536)

### LINKED ISSUE #38536: The grid’s Default View dropdown is showing as blank
### Preconditions (*)
Tested on this versions:
    1. Magento 2.4.6-p4
    2. Magento 2.4-develop branch

### Description (*)
When navigating to any grid page, such as the product or order grid, the user can create new views by selecting the 'Default view' dropdown menu. However, after creating a new view and naming it 'filter', it is saved in the database but not displayed in the dropdown menu. Additionally, upon refreshing the page, the entire view section becomes blank.

This issue triggers an error in the console, specifically a TypeError that states "number 0 is not a function."

Screenshot 1:  Before refreshing the page
image

Screenshot 2:  After refreshing the page
image

### Steps to reproduce (*)
1. Access the Magento admin panel and navigate to any grid.
2. Navigate to the "Columns" section and select or deselect any field.
3. Click on the default view dropdown menu and then select the "Save View As..." option.
4. Name the view as 'filter' and then press Enter. You may notice that it does not appear in the dropdown menu.
5. Subsequently, after refreshing the page, all the views disappear.

Screenshot 3:
image

Screenshot 4:
image

Screenshot 5:
image

Screenshot 6:
image

### Expected result (*)
1. Naming a view as ‘filter’ should not cause any issue and should show the default view dropdown correctly.

### Actual result (*)
1. Naming a view as 'filter' results in the default view dropdown showing as blank.

### Additional information (*)

**File path**: vendor/magento/module-ui/view/base/web/js/lib/knockout/bindings/i18n.js

After debugging the issue, I discovered that, In the ‘**execute**’ function of the 18n.js file, it translates the text using **‘$.mage.__(original)’**. Therefore, when naming the view as ‘**filter**’, it converts it into the function ‘ **ƒ filter() { [native code] }** ‘.

In the ‘**setText**’ function, it sets the texts in the element, but it seems to be triggering an error. It's unclear why it's converting the word "filter" into a function.

Screenshot 7:
image

Screenshot 8:
test

### PR DESCRIPTION
**Pull request by lbajsarowicz**
## Summary

`$.mage.__()` / `$.mage.translate.translate()` decides whether a string has a translation with:

```js
return typeof _data[text] !== 'undefined' ? _data[text] : text;
```

`_data` is the parsed `js-translation.json`. When a store has no JS translations, that file is `[]`, so `_data` is an **array**. Reading `_data[text]` walks the prototype chain, so any text matching an `Array.prototype` (or `Object.prototype`) member resolves to that member instead of `undefined`. For example `$.mage.__('filter')` returns the native `Array.prototype.filter` function rather than the string `"filter"`.

This breaks the admin grid "Save View As…" feature reported in #38536: naming a view `filter` (or `map`, `forEach`, …) feeds a function into the i18n binding's `setText`, throwing `TypeError: number 0 is not a function` and leaving the Default View dropdown blank after refresh.

## What the fix does

Replaces the loose `typeof … !== 'undefined'` lookup with an own-property check:

```js
return Object.prototype.hasOwnProperty.call(_data, text) ? _data[text] : text;
```

Only real entries in the dictionary are treated as translations; inherited prototype members never are. `Object.prototype.hasOwnProperty.call(...)` is used (rather than `_data.hasOwnProperty(...)`) to stay compliant with the `no-prototype-builtins` ESLint rule and to remain correct even when `_data` is an array.

## Test Plan

- Extended `dev/tests/js/jasmine/tests/lib/mage/translate.test.js` with a regression case asserting that `filter`, `map`, `forEach`, `constructor`, and `hasOwnProperty` return the untranslated text instead of inherited members.
- Existing translate specs (string / array / object / two-arg `add`) continue to pass — real translations are unaffected.
- Verified behaviour against empty-array, polluted-array, and object dictionaries.

Fixes #38536

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests
