### ISSUE TITLE
Magento 2.2.5 blank theme compilation error

### ISSUE THREAD

**Issue by Tofandel** [magento/magento2#16912]
Hello, after upgrading from magento 2.2.3 I had a need to recompile all less files, so I remove the view_preprocessed files and tried to recompile using a simple setup:static-content:deploy

But I got an error:
Compilation from source: vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @abs-checkout-tooltip-content-position-top is undefined in file

So I checked and indeed the variable is not defined in the file, but it is defined in vendor/magento/theme-frontend-luma/web/css/styles-m.less

So my guess is this declaration is missing in the blank theme's styles-m.less

```less
@abs-checkout-tooltip-content-position-top: {
    .lib-css(right, @checkout-tooltip-content-mobile__right);
    .lib-css(top, @checkout-tooltip-content-mobile__top);
    left: auto;

    &:before,
    &:after {
        .lib-arrow(
            @_position: top,
            @_size: @checkout-tooltip-icon-arrow__font-size,
            @_color: @checkout-tooltip-content__background-color
        );
        .lib-css(margin-top, @checkout-tooltip-icon-arrow__left);
        .lib-css(right, @indent__s);
        left: auto;
        top: 0;
    }

    &:before {
        .lib-css(border-bottom-color, @checkout-tooltip-content__border-color);
    }

    &:after {
        .lib-css(border-bottom-color, @checkout-tooltip-content__background-color);
        top: 1px;
    }
}
```
### Preconditions

1. Magento 2.2.5
2. A Magento blank theme child

### Steps to reproduce

1. Delete the cache and the preprocessed files
2. Delete the folder lib/web/design/frontend/ to erase all precompiled less files (Because why magento doesn't do this automatically on setup:upgrade is ununderstandable :angry: )
3. Run php bin/magento setup:upgrade
4. Run php bin/magento setup:di:compile
5. Run php bin/magento php bin/magento setup:static-content:deploy 

### Expected result
A compilation success

### Actual result
A compilation error:
Compilation from source: vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @abs-checkout-tooltip-content-position-top is undefined in file

**Comment by magento-engcom-team** [comment]
Hi @Tofandel. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://github.com/magento/magento2/wiki/Magento-Contributor-Assistant) documentation.

@Tofandel do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by Tofandel** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @Tofandel. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @Tofandel, here is your [Magento instance](https://i-16912-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-16912-2-2-5.engcom.dev.magento.com/admin](https://i-16912-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by Tofandel** [comment]
@magento-engcom-team yes

**Comment by ghost** [comment]
@Tofandel, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
![default](https://user-images.githubusercontent.com/40756187/42941438-78a4a80a-8b65-11e8-9ff3-0edb00e50ff8.png)

**Comment by Tofandel** [comment]
Okay so I'm reopening the issue as this happened again on my test server with a fresh install and vendor directory wiped..
I added one step to reproduce.

If you can't reproduce please check the file I indicated as it is indeed erroneus, thank you.

And by the way, we can't actually reopen issues.. https://github.com/isaacs/github/issues/583

**Comment by hostep** [comment]
@Tofandel: there is no directory `lib/web/design/frontend/` in Magento2, are you sure it's the correct one? I just tested this on a clean 2.2.5 and after running `setup:static-content:deploy` I can not see that directory.
Usually there are 3 directories you should clear before running `setup:static-content:deploy` and those are: `var/view_preprocessed/`, `pub/static/frontend/` and `pub/static/adminhtml/`.

Please make sure you don't have a 3rd party module or theme which is interfering here.

**Comment by ghost** [comment]
@Tofandel, the issue is reopened. But, as @hostep has mentioned, it seems like you have some custom modules. Please try to reproduce your issue on a clean Magento installation and update the steps to reproduce.

**Comment by ghost** [comment]
@Tofandel, we are closing this issue due to inactivity. If you'd like to update it, please reopen the issue.
