### PR TITLE
ISSUE 25680 Fixes console error on index page

### PR DESCRIPTION
**Pull request by duckchip**
### Description (*)

Since the requirejs-config block got removed in the layout file of the swagger index page, errors are thrown in the console log. To fix this, we also remove the `theme.active.editor` block for the swagger index page, which is defined in the `Magento/Ui/view/base/layout/default.xml` file.

### Fixed Issues (if relevant)

1. magento/magento2#25680: Console log error on Swagger page in 2.3.3

### Manual testing scenarios (*)

1. ... Go to /swagger endpoint of clean magento 2.3-develop instance 
2. ... Check the console log on the following error: `require.config is not a function`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by duckchip** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @duckchip, here is your [new Magento instance](https://pr-25682.instances.magento-community.engineering).
Admin access: [https://pr-25682.instances.magento-community.engineering/admin](https://pr-25682.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by duckchip** [comment]
Fix confirmed in testing environment

**Comment by kalpmehta** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, here is your [Magento instance](https://i-25682-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25682-2-3-develop.instances.magento-community.engineering/admin](https://i-25682-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by kalpmehta — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @kalpmehta, thank you for the review.
[ENGCOM-6307](https://jira.corp.magento.com/browse/ENGCOM-6307) has been created to process this Pull Request
:eight_spoked_asterisk: @kalpmehta, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed.

**Review by krzksz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-6307](https://jira.corp.magento.com/browse/ENGCOM-6307) has been created to process this Pull Request

**Comment by deepaksnair** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @deepaksnair. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by deepaksnair** [comment]
Hello all, I am still getting error on swagger landing page, I have attached a screenshot and error, please have a look

```
[2020-06-03 17:01:46] main.ERROR: Unable to resolve the source file for 'frontend/Magento/luma/en_US/Magento_Swagger/swagger-ui/css/swagger-ui.css.map' [] []
[2020-06-03 17:01:46] main.CRITICAL: Unable to resolve the source file for 'frontend/Magento/luma/en_US/Magento_Swagger/swagger-ui/css/swagger-ui.css.map' [] []
[2020-06-03 17:01:47] main.ERROR: Unable to resolve the source file for 'frontend/Magento/luma/en_US/Magento_Swagger/swagger-ui/js/swagger-ui-bundle.js.map' [] []
[2020-06-03 17:01:47] main.CRITICAL: Unable to resolve the source file for 'frontend/Magento/luma/en_US/Magento_Swagger/swagger-ui/js/swagger-ui-bundle.js.map' [] []
[2020-06-03 17:01:47] main.ERROR: Unable to resolve the source file for 'frontend/Magento/luma/en_US/Magento_Swagger/swagger-ui/js/swagger-ui-standalone-preset.js.map' [] []
[2020-06-03 17:01:47] main.CRITICAL: Unable to resolve the source file for 'frontend/Magento/luma/en_US/Magento_Swagger/swagger-ui/js/swagger-ui-standalone-preset.js.map' [] []
```

Screenshot from 2020-06-03 22-28-42
