### ISSUE TITLE
Rolled back db now i can't backup

### ISSUE THREAD

**Issue by zamboni084** [magento/magento2#3451]
Hi

I rollback my db and now when i try to run a backup from admin it does not work.There is also no list of backups on the backup page(System>Backups)

I enter a name for the backup and click ok and nothing happens.

Browser console i get.

TypeError: this.modal.find(...).validation is not a function
    this.modal.find('#backup-form').validation({

Thanks

**Comment by tseven** [comment]
I'm seeing the same error but on a fresh install.
![n3x7](https://cloud.githubusercontent.com/assets/311287/14413538/0045dfa8-ff32-11e5-8b13-af0dd5a8ac1e.jpg)

This error occurs in development and production mode on multiple servers, apache and nginx.

**Comment by andidhouse** [comment]
Hi there,

we have exact the same problem when trying to backup.

Did you find a solution for this?

**Comment by webspeaks** [comment]
I also have same error. Any update?

**Comment by mazhalai** [comment]
Thank you for reporting, we have created MAGETWO-52692 to investigate and fix.

**Comment by encircle** [comment]
Any news on this, or possible workaround? Client is trying to backup their system and getting nervous!

**Comment by flnative** [comment]
I have 2.0.7; I can no longer backup. Button does nothing. Also have the same JS error. I used to be able to backup.. I do not know when it stopped working from 2.0.1 to 2.0.7

I have this error in my browser console:
Uncaught TypeError: this.modal.find(...).validation is not a functionAdminBackup.backupConfig.backup-options.actionOk @ backup.js:148modal.jQuery.attr.html.modal.buttons.click @ backup.js:205jQuery.event.dispatch @ jquery.js:4624elemData.handle @ jquery.js:4292

**Comment by enochrod** [comment]
I have 2.0.7 and I am experiencing the same problem that flnative has reported.  I see the same error in Chrome Developer tools.  The backup button does nothing and the backups page does not show a list of backups that are in the var/backups folder.

**Comment by sergiojovanig** [comment]
Any update about this?

Same issue in Magento 2.1.1 after upgrading from 2.1.0.

**Comment by magento-engcom-team** [comment]
@zamboni084, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. If you'd like to update it, please reopen the issue.
We tested the issue on 2.3.0-dev, 2.2.0, 2.1.9

**Comment by reesmcivor** [comment]
I am experiencing the same issue on a 2.3.3 installation.
