### ISSUE TITLE
Console log error on Swagger page in 2.3.3

### ISSUE THREAD

**Issue by duckchip** [magento/magento2#25680]
### Preconditions

1. Magento 2.3.3
2. Swagger module installed

The following console error shows up when navigating to the swagger page on a blank Magento2.3.3:  `require.config is not a function`

This is because requirejs-config block got removed from the layout file for the swagger index page. 

An easy fix would be to also add the following line to the layout file, but I don't know whether that is the best solution.

`<referenceBlock name="theme.active.editor" remove="true" />`

This block is coming Ui module, and is defined in the `default.xml` file which results to be loaded on every page.

### Steps to reproduce

1. Go to /swagger endpoint on Magento 2.3.3

### Expected result

1. No console errors

### Actual result

1. ![Screen Shot 2019-11-21 at 10 44 03](https://user-images.githubusercontent.com/9752966/69326473-2241b200-0c4c-11ea-8a6e-6ee417883304.png)

**Comment by duckchip** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @duckchip. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @duckchip, here is your [Magento instance](https://i-25680-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-25680-2-3-develop.instances.magento-community.engineering/admin](https://i-25680-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by duckchip** [comment]
can be reproduced on clean 2.3-develop instance

**Comment by duckchip** [comment]
fix confirmed on testing environment

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @krishprakash 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-29038` were created

**Issue Available**: @krishprakash, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by VladimirZaets** [comment]
Hi @duckchip. Thank you for your report. 
The issue has been fixed in magento/magento2#25682 by @duckchip in 2.3-develop branch
Related commit(s):
 - [748de99356d5fcec2839f860484311255aac7d32](https://github.com/magento/magento2/commit/748de99356d5fcec2839f860484311255aac7d32)

The fix will be available with the upcoming 2.3.5 release.
