### PR TITLE
Fix undefined methods 'addClass' and `removeClass` on a PrototypeJS Element

### PR DESCRIPTION
**Pull request by markvds**
### Description
This problem was caused by 5a283e3ff9 and reported in #20843. The mentioned commit adds two lines in `js.phtml` with non existing methods: `panel.addClass(activePanelClass);` and `panel.removeClass(activePanelClass);`. Both methods do not exist in PrototypeJS and should have been `addClassName()` and `removeClassName()` respectively.

The incorrect method names cause a Javascript error 'Uncaught TypeError: panel.addClass is not a function' in the console and prevents the Edit Attribute form from saving.

Enabling the Swatches module, as mentioned in the issue, only solves the issue because it replaces the phtml file with its own file.

### Fixed Issues (if relevant)
1. magento/magento2#20843: Uncaught TypeError: panel.addClass is not a function when Swatches are disabled

### Manual testing scenarios
1. Disable Swatches modules (otherwise, the mentioned phtml file will not be used)
2. In admin, go to Stores > Attributes > Product
3. Click any attribute
4. Try to save the attribute
5. Nothing happens without the code change, but the attribute saves fine with the code change

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22560) <br/>All committers have signed the CLA.

**Review by orlangur — CHANGES_REQUESTED** [review]
@markvds please use `jQuery` equivalents instead.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by markvds** [comment]
@orlangur I cannot imagine that it makes the situation any better; it's all surrounded by PrototypeJS code. I think it would even make readibility worse.

**Comment by orlangur** [comment]
@markvds we don't need to add any new PrototypeJS-related code. Feel free to refactor any additional occurrences in file with jQuery.

**Comment by barryvdh** [comment]
@markvds Thank you for your PR.

@orlangur I would keep the bugfix PR as minimal as possible to make it clear what the intent and actual fix of this PR is. Also to make it easier to avoid merge conflicts etc.Refactoring the prototype should happen in a seperate PR imho.

**Comment by orlangur** [comment]
@barryvdh it will be minimal as I suggested since `jQuery` is already injected.

@markvds please apply necessary changes.

**Comment by jissereitsma** [comment]
My 50 cents: The proposed fix of @markvds is a bugfix. However, the suggestion of @orlangur would lead to a code enhancement. They are different things. I'm not sure if postponing the bugfix is a good idea, waiting for the code enhancement. On the other hand, I'm not sure how much work the refactoring the jQuery code would be. Just my 50 cents.

File: app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml [hunk 1]
```diff
@@ -45,11 +45,11 @@ function checkOptionsPanelVisibility(){
 
         if($('frontend_input') && ($('frontend_input').value=='select' || $('frontend_input').value=='multiselect')){
             panel.show();
-            panel.addClass(activePanelClass);
+            panel.addClassName(activePanelClass);
```
Comment (orlangur) [inline app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml]:
```suggestion
            jQuery(panel).addClass(activePanelClass);
```

**Review by orlangur — CHANGES_REQUESTED** [review]
Initial code was jQuery-style. There is no need to step back. Please replace all `addClassName/removeClassName`.

**Review by orlangur — CHANGES_REQUESTED** [review]
After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

**Comment by jissereitsma** [comment]
@orlangur You are awesome

**Comment by markvds** [comment]
I changed the PR. 

@orlangur I finally get your point. You basically say the method name was correct, but the context was wrong. I assumed the context was right but the method name was wrong. It's just a different view on the situation. Understanding your thoughts helps me in future PRs. Thanks for explaining!

**Comment by orlangur** [comment]
@markvds yep, sorry for confusion, will try to formulate better next time 🤝

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5020](https://jira.corp.magento.com/browse/ENGCOM-5020) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@markvds thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by soleksii** [comment]
:heavy_check_mark: QA Passed 

**Before:**

before

**After:**
after
