### ISSUE TITLE
Captcha Exception: Invalid method Magento\Framework\Session\Generic\Interceptor::isLoggedIn

### ISSUE THREAD

**Issue by joshuaadickerson** [magento/magento2#17777]
### Preconditions

1. Magento 2.2.5
2. PHP 7.1

### Steps to reproduce

1. Install B2B module (I don't know where else this is used and it isn't just a bug for B2B since the Captcha class is wrong)
2. Go to /company/account/create/ 
3. 

### Expected result

1. A "create account" page should appear

### Actual result

1. Get an exception

```
1 exception(s):
Exception #0 (InvalidArgumentException): Invalid method Magento\Framework\Session\Generic\Interceptor::isLoggedIn(Array
(
)
)

Exception #0 (InvalidArgumentException): Invalid method Magento\Framework\Session\Generic\Interceptor::isLoggedIn(Array
(
)
)
#0 /var/www/html/generated/code/Magento/Framework/Session/Generic/Interceptor.php(37): Magento\Framework\Session\SessionManager->__call('isLoggedIn', Array)
#1 /var/www/html/vendor/magento/module-captcha/Model/DefaultModel.php(224): Magento\Framework\Session\Generic\Interceptor->__call('isLoggedIn', Array)
#2 /var/www/html/vendor/magento/module-captcha/Model/DefaultModel.php(128): Magento\Captcha\Model\DefaultModel->isUserAuth()
#3 /var/www/html/vendor/magento/module-captcha/Block/Captcha/DefaultCaptcha.php(70): Magento\Captcha\Model\DefaultModel->isRequired()
#4 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Captcha\Block\Captcha\DefaultCaptcha->_toHtml()
#5 /var/www/html/vendor/magento/module-captcha/Block/Captcha.php(52): Magento\Framework\View\Element\AbstractBlock->toHtml()
#6 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Captcha\Block\Captcha->_toHtml()
#7 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('captcha')
#9 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('captcha')
#10 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('captcha')
#11 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('captcha', false)
#12 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('captcha', false)
#13 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('form.additional...', false)
#14 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('form.additional...')
#15 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('form.additional...')
#16 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('form.additional...', true)
#17 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('form.additional...', true)
#18 /var/www/html/vendor/magento/module-company/view/frontend/templates/company/account/create.phtml(224): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form.additional...')
#19 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#20 /var/www/html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Company\Block\Company\Account\Create), '/var/www/html/v...', Array)
#21 /var/www/html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#22 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#23 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#24 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('company_account...')
#25 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('company_account...')
#26 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('company_account...')
#27 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('company_account...', false)
#28 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout\Interceptor->renderElement('company_account...', false)
#29 /var/www/html/vendor/magento/module-theme/view/frontend/templates/template.phtml(8): Magento\Framework\View\Element\AbstractBlock->getChildHtml('', false)
#30 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#31 /var/www/html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template), '/var/www/html/v...', Array)
#32 /var/www/html/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/html/v...')
#33 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#34 /var/www/html/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#35 /var/www/html/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('company.account...')
#36 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('company.account...')
#37 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('company.account...')
#38 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('company.account...', false)
#39 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('company.account...', false)
#40 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content', false)
#41 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#42 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#43 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#44 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#45 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main', false)
#46 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#47 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#48 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', false)
#49 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main', false)
#50 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns', false)
#51 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#52 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#53 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', false)
#54 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false)
#55 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#56 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#57 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#58 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', false)
#59 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false)
#60 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#61 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#62 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#63 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#64 /var/www/html/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#65 /var/www/html/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root', false)
#66 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#67 /var/www/html/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#68 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#69 /var/www/html/vendor/magento/framework/View/Layout.php(955): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#70 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#71 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#72 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#73 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#74 /var/www/html/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#75 /var/www/html/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#76 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#77 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#78 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#80 /var/www/html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#82 /var/www/html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#83 /var/www/html/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#84 {main}
```

In `Magento\Captcha\Model\DefaultModel` the SessionManagerInterface does not implement `isLoggedIn`. It should probably use `Magento\Customer\Model\Session` instead

**Comment by magento-engcom-team** [comment]
Hi @joshuaadickerson. Thank you for your report. 
To help us process this issue please make sure that you provided the following information:
- [ ] Summary of the issue
- [ ] Information on your environment
- [ ] Steps to reproduce
- [ ] Expected and actual results

Please make sure that the issue is reproducible on the vanilla Magento instance following **Steps to reproduce**. To deploy vanilla Magento instance on our environment, please, add a comment to the issue: 

`@magento-engcom-team give me {$VERSION} instance` 

where `{$VERSION}` is [version tags](https://github.com/magento/magento2/tags) (starting from 2.2.0+) or develop branches (2.2-develop +). 
For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation.

@joshuaadickerson do you confirm that you was able to reproduce the issue on vanilla Magento instance following steps to reproduce?
- [ ] yes
- [ ] no

**Comment by joshuaadickerson** [comment]
@magento-engcom-team give me 2.2.5 instance

**Comment by magento-engcom-team** [comment]
Hi @joshuaadickerson. Thank you for your request. I'm working on Magento 2.2.5 instance for you

**Comment by magento-engcom-team** [comment]
Hi @joshuaadickerson, here is your [Magento instance](https://i-17777-2-2-5.engcom.dev.magento.com).
Admin access: [https://i-17777-2-2-5.engcom.dev.magento.com/admin](https://i-17777-2-2-5.engcom.dev.magento.com/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by ghost** [comment]
@joshuaadickerson,  thank you for your report. Please follow these guidelines for proper tracking of your issue. You can report Commerce-related issues in one of two ways:
You can use the Support portal associated with your account
or
If you are a Partner reporting on behalf of a merchant, use the Partner portal.

GitHub is intended for Magento Open Source users to report on issues related to Open Source only. There are no account management services associated with GitHub.
