### ISSUE TITLE
Cron job fatal error every day at 00:00

### ISSUE THREAD

**Issue by peterhirn** [magento/magento2#3033]
I'm running the 2.0 branch with HHVM. The cron job fails every day at 00:00 with the following error:

```
Fatal error: Class undefined: Magento\SalesRule\Crone\AggregateSalesReportCouponsData in /data/magento2/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php on line 97
```

**Comment by mazhalai** [comment]
@peterhirn do you have any other crons scheduled?

**Comment by peterhirn** [comment]
Nothing beside the default debian jessie cron jobs. I had some other issues with cron jobs after a migration from 1.x, this might be related. I'll check this with a default setup and update this issue afterwards.

**Comment by peterhirn** [comment]
I upgraded to 2.0.1 and the issue is gone.

**Comment by magefan** [comment]
Bug is still in 2.0.2

You need to edit file vendor/magento/module-sales-rule/etc/crontab.xml
and change line 10

Replace
Magento\SalesRule\Crone\AggregateSalesReportCouponsData
with
Magento\SalesRule\Cron\AggregateSalesReportCouponsData

---

Crone -> Cron

then clean magento cache
