### ISSUE TITLE
File Upload stops in Backend

### ISSUE THREAD

**Issue by Olek89** [magento/magento2#10689]
### Preconditions

1. M2 2.1.8
2. PHP 7.0.22

### Steps to reproduce

1. Go in produkt
2. Add Links
3. go to search for Data and starts upload

### Expected result

1. the files should upload, but it stops after maybe 20mb or 80 sec.

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/31250340/29786913-3261f1fa-8c2d-11e7-9de4-c746d15be37a.png)

**Comment by orlangur** [comment]
Do you see any errors in Network tab of Dev Tools? Did you change all necessary `php.ini`/web server settings accordingly?

**Comment by Sam-PUMP** [comment]
Error is 
```postData.data.set is not a function. (In 'postData.data.set('param_name', this.paramName)', 'postData.data.set' is undefined)```

**Comment by Olek89** [comment]
In the serverconfiguration it should be everything well.
Is it an error in M2?
Could it be resolved?

**Comment by orlangur** [comment]
Are you using Safari browser? Duplicate of https://github.com/magento/magento2/issues/10804 then.

**Comment by Olek89** [comment]
I am Using the Google Chrome, but i also testet in IE, Safari, or on mac, everytimes the same.

**Comment by Olek89** [comment]
After Updating to 2.1.9 the problem is also hapining, still after 75 Sec. the upload process canceling.

**Comment by orlangur** [comment]
@Olek89 is https://github.com/magento/magento2/issues/10689#issuecomment-325459867 what you see or in your case there are no errors shown in logs or browser console?

**Comment by Olek89** [comment]
@orlangur thank you, no logs, the java script only stopping i think. browser or webserver nothing logging.

**Comment by orlangur** [comment]
> the java script only stopping

Without any error in browser console / Network tab of Dev Tools or like described in https://github.com/magento/magento2/issues/10689#issuecomment-325459867 ?

**Comment by Olek89** [comment]
did you have an tutorial how i can test it?

**Comment by orlangur** [comment]
Just different tabs of Dev Tools: https://developer.chrome.com/devtools

Main interest for us in scope of this issue are Network and Console tabs.

**Comment by Olek89** [comment]
thank you a problem in console:
![2017-09-17 12_39_52-anatomie des bewegungsapparates -download-version _ produkte _ inventory _ produ](https://user-images.githubusercontent.com/31250340/30520075-990e5a74-9ba5-11e7-84b9-135cb675c565.png)

**Comment by orlangur** [comment]
Could you check Network tab also to see if all the JS files loaded successfully? (no red lines with 404 HTTP Not Found and such).

Closest issue I managed to google is https://stackoverflow.com/questions/40411835/cannot-read-property-getbitrate-of-null-in-jquery-fileupload-js-using-filegato, probably upgrading `jquery.fileupload` can help.

**Comment by Olek89** [comment]
i tink in the network tab is no issue
How can i upgrade?

![2017-09-17 13_03_33-](https://user-images.githubusercontent.com/31250340/30520179-c1f547c4-9ba8-11e7-8c5a-ae7288cc7925.png)

**Comment by orlangur** [comment]
Replace `jquery.fileupload` files with newer ones, for the sake of experiment you can download them right from the demo page https://blueimp.github.io/jQuery-File-Upload/

**Comment by magento-engcom-team** [comment]
@Olek89 thank you for your bug report.
We've created internal ticket MAGETWO-75465 to track progress on the issue.

**Comment by Olek89** [comment]
Which Files i have to change?

**Comment by orlangur** [comment]
Anything containing `'jquery.fileupload'`, like
```
<!-- The basic File Upload plugin -->
<script src="js/jquery.fileupload.js"></script>
```

**Comment by Olek89** [comment]
i have changed it in  /httpdocs/pub/static/adminhtml/Magento/backend/de_DE/jquery/fileUploader/
But now i get these error

![image](https://user-images.githubusercontent.com/31250340/30603466-d81ec064-9d67-11e7-9893-2bcf31b21cb0.png)

**Comment by magento-engcom-team** [comment]
@Olek89, thank you for your report.     
    
Unfortunately, we are archiving this ticket now as it did not get much attention from both Magento Community and Core developers for an extended period. This is done in an effort to create a quality, community-driven backlog which will allow us to allocate the required attention more easily.

Please feel free to comment, reopen or create new ticket according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines) 
if you are still facing this issue on the latest `2.4-develop` branch. Thank you for collaboration.
