### ISSUE TITLE
Varnish VCL - bin/magento varnish:vcl:generate command generates vcl with deprecated value

### ISSUE THREAD

**Issue by shkoliar** [magento/magento2#23670]
### Preconditions (*)

1. PHP 7.2, MariaDB 10.3, Varnish 5.2.1
2. Tested with Magento 2.3.2 and  Magento 2.3.1

### Steps to reproduce (*)

1. Run command 
````bash
bin/magento varnish:vcl:generate --access-list localhost --backend-host localhost --backend-port 8080 --output-file var/default.vcl
````
2. Run commands
````bash
varnishadm vcl.load default var/default.vcl
varnishadm vcl.use default
````

### Expected result (*)

1. Contents of generated `var/default.vcl` file, pay attention to correct row `return (miss);`
````
...

sub vcl_hit {
    if (obj.ttl >= 0s) {
        # Hit within TTL period
        return (deliver);
    }
    if (std.healthy(req.backend_hint)) {
        if (obj.ttl + 300s > 0s) {
            # Hit after TTL expiration, but within grace period
            set req.http.grace = "normal (healthy server)";
            return (deliver);
        } else {
            # Hit after TTL and grace expiration
            return (miss);
        }
    } else {
        # server is not healthy, retrieve from cache
        set req.http.grace = "unlimited (unhealthy server)";
        return (deliver);
    }
}
````
2. Varnish `varnishadm` command loads and activates config.

### Actual result (*)

1.  Contents of generated `var/default.vcl` file, pay attention to deprecated `return (fetch);`
````
...

sub vcl_hit {
    if (obj.ttl >= 0s) {
        # Hit within TTL period
        return (deliver);
    }
    if (std.healthy(req.backend_hint)) {
        if (obj.ttl + 300s > 0s) {
            # Hit after TTL expiration, but within grace period
            set req.http.grace = "normal (healthy server)";
            return (deliver);
        } else {
            # Hit after TTL and grace expiration
            return (fetch);
        }
    } else {
        # server is not healthy, retrieve from cache
        set req.http.grace = "unlimited (unhealthy server)";
        return (deliver);
    }
}
````
2. Varnish `varnishadm` commands results with error 
````
Message from VCC-compiler:
Invalid return "fetch"
...
            return (fetch);
--------------------#####--


...in subroutine "vcl_hit"
...
sub vcl_hit {
----#######--


...which is the "vcl_hit" method
Legal returns are: "deliver" "fail" "miss" "pass" "restart" "synth"
Running VCC-compiler failed, exited with 2
VCL compilation failed
Command failed with error code 106
````

**Comment by shkoliar** [comment]
FYI, varnish VCL config generated from Magento admin panel has correct values. The issue is related only to `bin/magento varnish:vcl:generate` command.

**Comment by engcom-Bravo** [comment]
@magento give me 2.2-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo. Thank you for your request. I'm working on Magento 2.2-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Bravo, here is your [Magento instance](https://i-23670-2-2-develop.instances.magento-community.engineering).
Admin access: [https://i-23670-2-2-develop.instances.magento-community.engineering/admin](https://i-23670-2-2-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by magento-engcom-team** [comment]
:white_check_mark: Confirmed by @engcom-Bravo 
 Thank you for verifying the issue. Based on the provided information internal tickets `MC-18131`, `MC-18132` were created

**Issue Available**: @engcom-Bravo, _You will be automatically unassigned. Contributors/Maintainers can claim this issue to continue. To reclaim and continue work, reassign the ticket to yourself._

**Comment by shkoliar** [comment]
After digging in the source code for `bin/magento varnish:vcl:generate` cli command, I've found out that command line parameter --export-version responsible for vcl version output. 

To sum up, `--export-version` parameter, when omitted, defaults to Varnish 4, and to get vcl config for Varnish 5 we need to include that parameter with corresponding version value.

It would be good to add more information about  `varnish:vcl:generate` command to dev docs.

**Comment by shkoliar** [comment]
Dev docs have a note about actual command and its parameters, but no detailed description and defaults like for other commands. 

https://devdocs.magento.com/guides/v2.2/reference/cli/magento.html 
https://devdocs.magento.com/guides/v2.3/reference/cli/magento.html

**Comment by pniel-cohen** [comment]
FYI: I managed to reproduce the issue on Magento 2.3.2 when I exported the vcl file from the admin panel (Varnish 4). Solved it manually by editing the file & replacing the `fetch` with `miss` on `sub vcl_hit{...}`.
