### ISSUE TITLE
Single "Cart Price Rule" view hangs (spinning wheel), JS Error: 'data.some is not a function'

### ISSUE THREAD

**Issue by fwolfst** [magento/magento2#11298]
### Preconditions
1. `uname -a`
`Linux XXX 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
2. DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
3. magento 2.1.9 without sample data, migrated data from 1.5 -> 1.9 -> 2.x
4. mysql-server-5.7 (5.7.19-0ubuntu0.16.04.1) from ubuntu repository
5. php7.0 (7.0.24-1+ubuntu14.04.1+deb.sury.org+1)
6. (client firefox 54, but happens with other browsers, too)

### Steps to reproduce
1. In backend, click on "Marketing" -> "Cart Price Rules" (in our case a table with our ~ 20 rules appear)
2. Click on a single cart price rule to edit or inspect it
3. Observe the ever-spinning wheel (indicating ajax loading stuff afaik).
4. The JavaScript console shows an error (`data.some is not a function`, will attach call stack image below).

### Expected result
1. I expect to see the detail/edit view for a cart price rule.

### Actual result
1. I just see the ever-spinning wheel (indicating ajax loading stuff afaik).
2. The JavaScript console shows an error (`data.some is not a function`), indicating some select box is probably not being populated properly.
![error_cart_price_rules](https://user-images.githubusercontent.com/219373/31317398-aa4640b2-ac40-11e7-9933-95113af143fe.jpg)

There is no entry in `var/report`, and also everything under `log/` looks normal.

**Comment by fwolfst** [comment]
Seems to have been caused by another, not correctly updated plugin. Closing.

**Comment by gxiang** [comment]
Regarding to this, I have checked the select.js and it only check if the value is array without checking if value is defined or function, which seem insufficient and cause the error.

![image](https://user-images.githubusercontent.com/1803898/31650586-a0aba72a-b34a-11e7-9ff0-2d8e82e042b7.png)

**Comment by fwolfst** [comment]
So this means the code could be better guarded? Should I open an issue for that (I do not have enough insight into the development process/conventions here) or is it "somebody elses fault"?

**Comment by tr33m4n** [comment]
Also seeing this on v2.1.9. Adding an `isArray` check to `select.js` prevents the error, however it doesn't help us understand why it's happening

**Comment by sshymko** [comment]
Experiencing the same issue after upgrading to 2.1.9.

@fwolfst, @tr33m4n,
Could you please share the workaround?

**Comment by fwolfst** [comment]
@sshymko As far as I remember we had an incompatible plugin installed. I am sorry that I do not remember which one. Maybe you can start by deactivating all of your extensions (`bin/magento module:status` to list all plus the base ones). If that fixes the issue go on by reactivating some until you found the culprit - IF your issue actually resembles ours.

**Comment by sshymko** [comment]
Thanks for the suggestion, @fwolfst.
I was hoping to get some pointers on what faulty code to look for in 3rd party/custom modules.
Meanwhile, we'll use the workaround suggested by @tr33m4n to unblock the marketing team.

**Comment by tr33m4n** [comment]
@sshymko I think our issue was an old version of the Amasty Free Gift module, if you're using any Amasty extensions maybe check those first

**Comment by sshymko** [comment]
@tr33m4n 
Yep, we've got some promotion-related Amasty extensions. Was suspecting these too. Thanks!

**Comment by stansm** [comment]
For me it was Amasty extension. The fix is pretty simple - I've just moved

`<item name="options" xsi:type="array">`

on the same level as

`<item name="config" xsi:type="array">`

in ui_component definitions

Proper way is to create a new module, put fixed xml files under view/adminhtml/ui_component there.
