### ISSUE TITLE
Some theme features don't working after upgrading from 2.2.7 to 2.3.2

### ISSUE THREAD

**Issue by Goldstar215** [magento/magento2#23715]
### Summary (*)
I have upgraded Magento from 2.2.7 to 2.3.2, and after upgrade, some features don't working.

### Examples (*)
1. Tiny MCE doesn't working. It shows an error: wysiwygSetup is not defined.
2. Custom validator(password strength validator) doesn't working.
3. I can't access stores/configuration. When I access to it, it shows an error: Uncaught TypeError: this.rules[this.name] is not a function. And all actions doesn't work(sidebar menu, configuration accordion menu), so I can't use this.

**Comment by engcom-Charlie** [comment]
Hello @Goldstar215 ! Thank you for your report !
I was not able to reproduce this issue on Vanilla Magento instance . Probably all the problems that you describe arise from third-party modules.
The GitHub issue tracker is intended for Magento Core technical issues only.
Please refer to the [Community Forums](https://community.magento.com/) or the [Magento Stack Exchange](https://magento.stackexchange.com/),  for advice or general discussion about this issue.

**Comment by Goldstar215** [comment]
Hi @engcom-Charlie ! Thank you for your work.
I had made some mistakes and now, I made current admin theme to base on 2.3.2 default admin theme.
All features work well now, but only tinymce not working now.
Here is console error.

require.js:1895 GET http://127.0.0.1:10082/static/version1563263538/adminhtml/Bfm/deercreekseed/en_US/tinymce.js net::ERR_ABORTED 404 (Not Found)
req.load @ require.js:1895
load @ require.js:1639
load @ require.js:820
fetch @ require.js:810
check @ require.js:840
enable @ require.js:1143
enable @ require.js:1511
(anonymous) @ require.js:1128
(anonymous) @ require.js:132
each @ require.js:57
enable @ require.js:1090
init @ require.js:774
(anonymous) @ require.js:1416
setTimeout (async)
req.nextTick @ require.js:1755
localRequire @ require.js:1405
requirejs @ require.js:1737
(anonymous) @ (index):388
require.js:166 Uncaught Error: Script error for: tinymce
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)

I think this occurs in my custom modules, but I can't find this.
Could you please help me?

Thanks.
