### ISSUE TITLE
M 2.4.0 upgrading issue - Unable to apply patch Magento\Review\Setup\Patch\Schema\AddUniqueConstraintToReviewEntitySummary

### ISSUE THREAD

**Issue by jesperbrejning** [magento/magento2#29352]
### Preconditions

Install Magento 2.3.5 CE using composer
### Steps to reproduce
1. Run SQL command
```sql
INSERT INTO review*entity*summary 
(`entity*pk_value`, `entity_type`, `reviews_count`, `rating_summary`, `store*id`) 
VALUES (1, 1, 1, 1, 1),(1, 1, 1, 2, 1);
{code}
1. Follow a general upgrade flow <https://devdocs.magento.com/guides/v2.4/comp-mgr/cli/cli-upgrade.html] and upgrade to 2.4.0

(<ins>) Upgrade completed successfully
 (-)
{code:bash}
Unable to apply patch Magento\Review\Setup\Patch\Schema\AddUniqueConstraintToReviewEntitySummary for module Magento*Review. Original exception message: Warning: preg*match(): Compilation failed: invalid range in character class at offset 40 in /Users/max/srv/composer/m2ee.composer/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2779
{code}
**Overview**:

When upgrading from 2.3.5 to 2.4.0 and running **php bin/magento setup:upgrade**, the following error appears:

*Unable to apply patch Magento\Review\Setup\Patch\Schema\AddUniqueConstraintToReviewEntitySummary for module Magento_Review. Original exception message: Warning: preg_match(): Compilation failed: invalid range in character class at offset 40 in /home/babygear/www/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 2779*

This issue is caused by a regular expression used in Magento code, which is not compatible with PHP 7.3 and PHP 7.4 


{code:bash}
#SQLSTATE\[23000\]: [<sup>:]</ins>: 1062[</sup>\']<ins>\'([\d-\.]</ins>)\'#
```

 

Please find more details here [https://github.com/magento/magento2/issues/29352>

**Comment by hostep** [comment]
Hmm, that's interesting, the regex you refer to is [`#SQLSTATE\[23000\]: [^:]+: 1062[^\']+\'([\d-\.]+)\'#`](https://github.com/magento/magento2/blame/2.4.0/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2779)

I think you have a point here, the problem is inside the `[\d-\.]` character class, the range character `-` is considered a true range character because it wasn't specified as the last character in the group, so the solution is most likely to change the regex from:
```
#SQLSTATE\[23000\]: [^:]+: 1062[^\']+\'([\d-\.]+)\'#
```
to:
```
#SQLSTATE\[23000\]: [^:]+: 1062[^\']+\'([\d\-\.]+)\'#
```
or:
```
#SQLSTATE\[23000\]: [^:]+: 1062[^\']+\'([\d\.-]+)\'#
```

Could you test both these suggested regexes and let me know which ones fixes your issue?

For completeness sake, can you specify the PHP version and the version of the pcre library you are using.
You can find these on the command line using:
```
php --version
php -i | grep PCRE
```

Thanks!

**Comment by hostep** [comment]
I can very easily reproduce the problem using PHP 7.3 and 7.4 (it works on PHP 7.2) with:
```
$ php -r "preg_match('#SQLSTATE\[23000\]: [^:]+: 1062[^\']+\'([\d-\.]+)\'#', 'whatever');"
PHP Warning:  preg_match(): Compilation failed: invalid range in character class at offset 40 in Command line code on line 1

Warning: preg_match(): Compilation failed: invalid range in character class at offset 40 in Command line code on line 1
```

I'm using:
```
PCRE Library Version => 10.35 2020-05-09
PCRE Unicode Version => 13.0.0
```

This most likely happens because PHP 7.3 and 7.4 upgraded from the pcre library version 1 to version 2 and the last one is probably more stricter: https://php.watch/versions/7.3#pcre2

Thanks for the bug report, it's truly an import bug and hopefully somebody will fix this shortly (and search the entire codebase for other possible variants of this bug and also fix those)

**Comment by martysmojo** [comment]
Can confirm I see this bug with a 2.4. upgrade 

`$ php -i | grep PCRE
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 10.32 2018-09-10
PCRE Unicode Version => 11.0.0
PCRE JIT Support => enabled
PCRE JIT Target => x86 64bit (little endian + unaligned)
`

`$ php --version
PHP 7.3.20 (cli) (built: Jul 22 2020 09:57:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.1, Copyright (c) 2002-2020, by ionCube Ltd.
    with SourceGuardian v11.4.1, Copyright (c) 2000-2020, by SourceGuardian Ltd.
    with Zend OPcache v7.3.20, Copyright (c) 1999-2018, by Zend Technologies
`

**Comment by martysmojo** [comment]
To amend my other comment, I couldn't replicate this using vanilla Magento installs from 2.3.4 to 2.4.0 (the above case was 2.3.4 to 2.4.0) so its not clear why its failing to update in our case.

**Comment by fascinosum** [comment]
Hello @jesperbrejning, @hostep, @martysmojo 
thank you for your contribution. An internal ticket has been created to track this issue MC-36428
@martysmojo this issue can be reproduced using a specific data set

**Comment by magento-engcom-team** [comment]
Hi @jesperbrejning. 

Thank you for your report and collaboration!

The issue was fixed by Magento team. The fix was delivered into `magento/magento2:2.4-develop` branch(es).
Related commit(s):
 - [dd151d11f4d709abb91b82a5d4360aae651c20e3](https://github.com/magento/magento2/commit/dd151d11f4d709abb91b82a5d4360aae651c20e3)

The fix will be available with the upcoming `2.4.1` release.
