### ISSUE TITLE
Error to save product and category

### ISSUE THREAD

**Issue by willstorm** [magento/magento2#5042]
I'm running Magento 2.1.0-rc2
## Steps to reproduce
1. Install Magento from `develop` branch.
2. Select Single Store Mode.
3. Click to Add Product in catalog.
4. Fill the fields and click to save.
## Expected result
1. A product has been created.
## Actual result
1. Javascript throw an error: Uncaught TypeError: $.validator.validateSingleElement is not a function.

**Comment by mslabko** [comment]
Hi @willstorm 
I cannot reproduce it on rc2. Could you please try to clean browser cache? If it's not help please provide more detailed information.

**Comment by Asitis** [comment]
Had the same issue, cleared the browser cache and it works on 2.1.

**Comment by prasanthnatrajan** [comment]
still i am facing the same problem! i cant save any categories and products! please give me a solution!

**Comment by andimov** [comment]
@willstorm 
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
@prasanthnatrajan Please, check solution from the previous comment or create a new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines)
