### ISSUE TITLE
after upgrade magento from 2.0.8 to 2.1.1 via composer -  `Uncaught TypeError: define is not a function`

### ISSUE THREAD

**Issue by OlgaBurtyka** [magento/magento2#6524]
After upgrade magento from 2.0.8 to 2.1.1 via composer I get `Uncaught TypeError: define is not a function`. On magento 2.0.8 all was fine. After upgrade i see in all places this error "define is not a function". Can you help?
### Preconditions

1. Php version 7.0.7
2. 
### Actual result

1. [Screenshot, logs]
   ![m2 1 1](https://cloud.githubusercontent.com/assets/4771407/18316285/aeaa2642-7522-11e6-862a-ef19b5fce46d.png)

**Comment by andimov** [comment]
@OlgaBurtyka
Thank you for reporting!
Try to clear browser cache & data and reload this page.

**Comment by OlgaBurtyka** [comment]
@andimov  Did. Same. Most of script error is in  Magento_UI (for example static/frontend/p4/theme/en_US/Magento_Ui/js/lib/knockout/bindings/resizable.js)
![m2 1 2](https://cloud.githubusercontent.com/assets/4771407/18317145/e23988ce-7525-11e6-9663-deeed1738aed.png)
![m2 1 3](https://cloud.githubusercontent.com/assets/4771407/18317911/3f2697be-7528-11e6-9137-aab46912f662.png)

**Comment by andimov** [comment]
@OlgaBurtyka
Try to open this page in other browsers.

**Comment by OlgaBurtyka** [comment]
@andimov I opened. in chrome and firefox. Same. I can explain how I am update magento. I download zip with last magento 2.1.1. And in my magento replace composer.json to composer.json from magento 2.1.1 and then run composer update. After this run 

php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento indexer:reindex

Same  when i am updated to in magento 2.1.0. I have custom theme - was working fine o n magento 2.0.8.

**Comment by OlgaBurtyka** [comment]
@andimov  Don't understand why  js files not see main require.js file and function define. What difference in magento 2.08 and 2.1 in require-config.js?
![magento2_1_0](https://cloud.githubusercontent.com/assets/4771407/18355009/6f06c076-75f0-11e6-8922-a09bdaba060a.png)

**Comment by BaDos** [comment]
Hi @OlgaBurtyka 

Yes, requirejs-config.js has some differences.
Do you have the same problem on Luma theme?
It seems like your custom theme doesn't support Magento 2.1.x

**Comment by veloraven** [comment]
According to [contributor guide](http://devdocs.magento.com/guides/v2.1/contributor-guide/contributing.html), tickets without response for two weeks should be closed.
If this issue still reproducible please feel free to create the new one: format new issue according to the [Issue reporting guidelines](https://github.com/magento/magento2/wiki/Issue-reporting-guidelines): with steps to reproduce, actual result and expected result and specify Magento version.
