### ISSUE TITLE
Magento 2.3.4 Google Analytics Script Blocked

### ISSUE THREAD

**Issue by Ctucker9233** [magento/magento2#27464]
### Preconditions (*)

1. Magento 2.3.4  Vanilla Install
2. Latest Google Chrome

### Steps to reproduce (*)

1. Install Magento 2.3.4 via Softaculous Autoinstaller
2. Create Google Analytics property
3. Enter tracking code in Magento backend
4. Navigate to home page

### Expected result (*)

1. Everything works as it should and google analytics is not blocked
### Actual result (*)

1. Google Analytics is blocked, errors in console:

require.js:1895 GET https://handmadeorigins.com/pub/static/version1585184407/frontend/Handmade/handmade/en_US/Magento_GoogleAnalytics/js/google-analytics.js net::ERR_BLOCKED_BY_CLIENT
req.load @ require.js:1895
load @ require.js:1639
load @ require.js:820
fetch @ require.js:810
check @ require.js:840
enable @ require.js:1143
enable @ require.js:1511
(anonymous) @ require.js:1128
(anonymous) @ require.js:132
each @ require.js:57
enable @ require.js:1090
init @ require.js:774
(anonymous) @ require.js:1416
setTimeout (async)
req.nextTick @ require.js:1755
localRequire @ require.js:1405
window.require @ mixins.js:245
init @ main.js:24
(anonymous) @ main.js:96
_.each._.forEach @ underscore.js:150
(anonymous) @ main.js:79
apply @ main.js:76
fire @ jquery.js:3238
add @ jquery.js:3297
jQuery.fn.ready @ jquery.js:3548
jQuery.fn.init @ jquery.js:2973
jQuery.fn.init @ jquery-migrate.js:241
jQuery @ jquery.js:80
(anonymous) @ bootstrap.js:20
execCb @ require.js:1650
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
(anonymous) @ require.js:991
(anonymous) @ require.js:132
(anonymous) @ mixins.js:106
execCb @ require.js:1650
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
(anonymous) @ require.js:991
(anonymous) @ require.js:132
(anonymous) @ mixins.js:106
execCb @ require.js:1650
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
(anonymous) @ require.js:991
(anonymous) @ require.js:132
(anonymous) @ mixins.js:106
execCb @ require.js:1650
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
(anonymous) @ require.js:991
(anonymous) @ require.js:132
runCallbacks @ domReady.js:24
callReady @ domReady.js:35
pageLoaded @ domReady.js:50
load (async)
(anonymous) @ domReady.js:59
execCb @ require.js:1650
check @ require.js:866
enable @ require.js:1143
init @ require.js:774
callGetModule @ require.js:1170
completeLoad @ require.js:1544
onScriptLoad @ require.js:1671
load (async)
req.load @ require.js:1882
load @ require.js:1639
load @ require.js:820
fetch @ require.js:810
check @ require.js:840
enable @ require.js:1143
enable @ require.js:1511
callPlugin @ require.js:1075
fetch @ require.js:810
check @ require.js:840
enable @ require.js:1143
enable @ require.js:1511
(anonymous) @ require.js:1128
(anonymous) @ require.js:132
each @ require.js:57
enable @ require.js:1090
init @ require.js:774
(anonymous) @ require.js:1416
setTimeout (async)
req.nextTick @ require.js:1755
localRequire @ require.js:1405
window.require @ mixins.js:245
(anonymous) @ (index):458
Show 82 more frames
main.js:37 Error: Script error for: Magento_GoogleAnalytics/js/google-analytics
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)

**Comment by Ctucker9233** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @Ctucker9233. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @Ctucker9233, here is your [Magento instance](https://i-27464-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27464-2-4-develop.instances.magento-community.engineering/admin_b502](https://i-27464-2-4-develop.instances.magento-community.engineering/admin_b502)
Login: `3161799f` Password: `18ba841bfd29`
Instance will be terminated in up to 3 hours.

**Comment by Ctucker9233** [comment]
I confirm the same frontend error appears after configuring Google Analytics in 2.4-develop

**Comment by sudheers-kensium** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @sudheers-kensium, here is your [Magento instance](https://i-27464-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-27464-2-4-develop.instances.magento-community.engineering/admin_e564](https://i-27464-2-4-develop.instances.magento-community.engineering/admin_e564)
Login: `00b03f7a` Password: `033de920b0de`
Instance will be terminated in up to 3 hours.

**Comment by sudheers-kensium** [comment]
@Ctucker9233 I am not able to reproduced the issue on Magento 2.4-develop instance.

Please provide more details and screenshots.

**Comment by Ctucker9233** [comment]
[Google Analytics Set Up](https://drive.google.com/open?id=1ejeN_M7jkdYdFZ6Hgicqt_7yBpHCr2vQ)
[Console Log](https://drive.google.com/open?id=1j-g9N1q-aZdHP9cJ4lGYcQc8nRVBaAPF)

**Comment by Ctucker9233** [comment]
I've put two screenshots there of my Google Analytics configuration and what the console shows. What other sorts of details would be useful?

**Comment by Ctucker9233** [comment]
#12428
Not the first time this issue has been encountered, and apparently never solved

**Comment by Ctucker9233** [comment]
@magento-engcom-team I've tried disabling the Dotmailer Module as suggested by other related issues, that did not work. I think it's the same ad-blocker problem that is mentioned in the related issue I linked. They are marked as solved, but clearly the fix did not solve the problem.

**Comment by hostep** [comment]
@Ctucker9233: do you have an adblocker installed? Some adblockers block google analytics by default. So if you do have one installed, try to disable it and see if the error does still occurs or not. If the error is fixed by disabling the addblocker, it means there is no bug in Magento.

**Comment by Ctucker9233** [comment]
@hostep That works for me, but what about any potential customers that choose to have ad-blockers or tracking blockers?

**Comment by hostep** [comment]
Well, if they choose not to be tracked, then they won't be tracked, it's their choice.
Shop owners should not assume that frontend javascript tracking services will be 100% accurate, because they never will be.
