### ISSUE TITLE
Form with a field named 'action' throws error when submitted

### ISSUE THREAD

**Issue by iuwqyir** [magento/magento2#26554]
When developing a custom payment method module, I needed to send order data to the payment gateway. To do that, I appended a form to the checkout body and submitted it.

If one of the form fields is named `action`, then an error will be thrown on form submittion.

### Preconditions (*)

1. Tested on Magento 2.3.3, but it also occurs on Magento 2.1.x and 2.2.x

### Steps to reproduce (*)

1. Go to checkout
2. Paste this in the console
``` 
    var form = "
        <form name='test_form' id='test-data-form'  action='https://example.com' method='post'>
            <input type='text' name='action' value='test' hidden />
            <input type='submit' value='Submit' hidden />
        </form>
    ";

    jQuery('body').append(form);
    jQuery('#test-data-form').submit();
```

### Expected result (*)

1. Form is submitted

### Actual result (*)

1. Form is not submitted and error is thrown: : `Uncaught TypeError: url.replace is not a function`

![form-submit-error](https://user-images.githubusercontent.com/16590638/73213337-acc8f500-4158-11ea-9611-4cc415536303.png)

### Possible solution
Files `Magento_Customer/view/frontend/web/js/customer-data.js` and `Magento_Catalog/view/frontend/web/js/storage-manager.js` access a form's `action` attribute incorrectly.
The code `event.target.action` returns the form field with the name `action` instead of the value of attribute `action`.

The correct way to ask for the element's `action` attribute would be
`event.target.getAttribute('action')`
or using jquery
`$(event.target).attr('action')`

**Comment by iuwqyir** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @iuwqyir. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @iuwqyir, here is your [Magento instance](https://i-26554-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-26554-2-4-develop.instances.magento-community.engineering/admin_3495](https://i-26554-2-4-develop.instances.magento-community.engineering/admin_3495)
Login: `53fd45dc` Password: `cdff791c63c2`
Instance will be terminated in up to 3 hours.

**Comment by iuwqyir** [comment]
On Magento 2.4 the issue still persists, however it manifests in a different place. This error is thrown:

![error_on_submit](https://user-images.githubusercontent.com/16590638/73292367-9aa78f00-420a-11ea-91bb-ed56dec39a4d.png)

This is because in [common.js](https://github.com/magento/magento2/blob/2.4-develop/lib/web/mage/common.js#L28) the form's `action` prop is acquired using `.prop('action')` instead of `.attr('action')`

**Comment by Nazar65** [comment]
Hi @iuwqyir why you do like that ? why you just not send the ajax request with data ?

**Comment by engcom-Bravo** [comment]
Hello @iuwqyir 

This behaviour is not supported by Magento2.
Please, use [ajax request](https://api.jquery.com/jQuery.post/).

We have to close this issue.

Thank you for collaboration
